<div class="row-fluid">
    <h1 class="text-center"> Welcome to Area 6 </h1>
</div>

<table class="table table-striped table-bordered table-condensed text-center">
			<thead>
                            <tr>
				<th class="text-center">Id</th>
                                <th class="text-center">Título</th>
                                <th class="text-center">Contenido</th>
                                <th class="text-center">Fecha de creación</th>
                                <th class="text-center">Editar</th>
                                <th class="text-center">Eliminar</th>
                            </tr>
			</thead>
			<tbody>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tbody>
</table>
